enum NotificationType {
    TRANSACTION_ALERT,
    BILL_REMINDER,
    BUDGET_LIMIT,
    BUDGET_DUE,
    SAVING_GOAL_DUE,
    SAVING_GOAL_LIMIT,
    DEBT_REMINDER,
    LOAN_REMINDER,
    RECURRENCE_ALERT,
    INCOME_ALERT,
    EXPENSE_ALERT,
    ACCOUNT_ALERT,
    SYSTEM_ALERT
}